language: python
sudo: false
python: 2.7


env:
  - SECRET_TOKEN=407865243842415070840827608579584201612907649740618373828
  
before_install:
  - rvm install 2.5
  - rvm use 2.5
  - gem install hiptest-publisher
  - hiptest-publisher -c python-unittest.conf --token=$SECRET_TOKEN --only=tests --test-run-id=235600

script:
 - python bootstrap.py
 - bin/buildout
 - bin/test --with-xunit

after_script:
  - hiptest-publisher -c python-unittest.conf --token=$SECRET_TOKEN --push="nosetests.xml" --test-run-id=235600
